## Broadcasting, Universal Functions, Sorting, and Searching

In [1]:
#import numpy
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
# Add 2 to the array
add_result=a+2
print(add_result)

[3 4 5 6 7]


In [4]:
# Divide array by 10
result=a/2
print(result)

[0.5 1.  1.5 2.  2.5]


In [5]:
a=np.array([1,2,3])
b=5
print(a+b)

[6 7 8]


In [6]:
# raise to the power 2
print(a)
power_result=a**2
print(power_result)

[1 2 3]
[1 4 9]


In [7]:
# sine
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [8]:
# Sorting
arr = np.array([4, 2, 7, 1, 5])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 4 5 7]


In [9]:
arr = np.array([[4, 2, 7],
                [1, 5, 3]])

# Sort each row
sorted_arr = np.sort(arr, axis=1)

print(sorted_arr)

[[2 4 7]
 [1 3 5]]


In [10]:
import numpy as np

arr = np.array([[4, 2, 7],
                [1, 5, 3]])

# Sort each column
sorted_arr = np.sort(arr, axis=0)
print(sorted_arr)

[[1 2 3]
 [4 5 7]]


In [11]:
# Getting Indices of Sorted Elements
arr = np.array([4, 2, 7, 1, 5])
sorted_indices = np.argsort(arr)
print(sorted_indices)

[3 1 0 4 2]


In [12]:
arr = np.array([10, 5, 8, 12, 3])
# Find indices of values satisfying a condition
print(np.where(arr > 6))

(array([0, 2, 3], dtype=int64),)


In [13]:
arr = np.array([10, 5, 8, 10, 3, 5])

# Get unique values from the array
print(np.unique(arr))

[ 3  5  8 10]


In [14]:
arr = np.array([10, 5, 8, 12, 3])

# Check if a value exists in the array
value_to_search = 8
result = np.isin(value_to_search, arr)
print(result)

True


In [15]:
## Challenge

import numpy as np


a = np.array([3, 6, 9, 12, 15])


# Adding a scalar (7) to each element in the array

c=a+7
print("after adding 7 ",c)

# Computing the cos of each element in the array
b=np.cos(a)
print("after computing cos",b)

# Sorting

sorted_a = np.sort(a)
print("After Sorted ",sorted_a)
#Searching 8 in the array
print("The Number 8 Exist :",np.isin(8,a)) 


after adding 7  [10 13 16 19 22]
after computing cos [-0.9899925   0.96017029 -0.91113026  0.84385396 -0.75968791]
After Sorted  [ 3  6  9 12 15]
The Number 8 Exist : False
