## Linear algebra with Numpy: dot product, matrix multiplication, inverse, transpose

In [ ]:
import numpy as np

In [5]:
import numpy as np

a = np.array([2, 3])
b = np.array([4, 5])

dot_product = np.dot(a, b)
print(dot_product)  # Output: 23 (2*4+3*5)


23


In [2]:
import numpy as np

A = np.array([[2, 3],
              [4, 5]])
B = np.array([[6, 7],
              [8, 9]])

matrix_product = np.matmul(A, B)

print(matrix_product)
# Output:
# [[36 41]
#  [64 73]]


[[36 41]
 [64 73]]


In [3]:
import numpy as np

A = np.array([[4, 7],
              [2, 6]])

inverse_A = np.linalg.inv(A)
print(inverse_A)


[[ 0.6 -0.7]
 [-0.2  0.4]]


Formula:
A⁻¹ = (1 / (ad - bc)) * |  d  -b |
                        | -c   a |


In [4]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

transpose_A = A.T

print(transpose_A)
# Output:
# [[1 3]
#  [2 4]]


[[1 3]
 [2 4]]
