## Arrays and Basic Operations

In [15]:
# import numpy
import numpy as np

In [16]:
# Try to multiply two lists
a=[1,2,3,4,5]
b=[2,3,4,5,6]


In [17]:
#Coverting to numpy array and then multiply
a=np.array(a)
b=np.array(b)
a*b

array([ 2,  6, 12, 20, 30])

In [18]:
#Creating the numpy array single and multidimensional
c=np.array([1,2,3])
d=np.array([[9.1,8.2,7.3],[2.4,4.5,6.7]])
print(c)
print(d)

[1 2 3]
[[9.1 8.2 7.3]
 [2.4 4.5 6.7]]


In [20]:
# Get dimension
d.ndim

2

In [21]:
#Get shape
c.shape

(3,)

In [22]:
#Get type
a.dtype

dtype('int32')

In [8]:
e=np.array([1,2,3],dtype='int16')
e.dtype

dtype('int16')

In [9]:
#Get size
b.itemsize

4

In [25]:
# Challenge
import numpy as np

# Creating numpy arrays (single and multidimensional)
c = np.array([1, 2, 3])
d = np.array([[9.1, 8.2, 7.3], [2.4, 4.5, 6.7]])

# Get dimension of array c
print(c.ndim)

# Get shape of array c
print(c.shape)

# Get data type of array a
print(c.dtype)

# Create an array e with a specific data type
e=np.array([10,20,30],dtype='int16')
print(e.dtype)

# Get size (in bytes) of elements in array b

print(b.itemsize)

1
(3,)
int32
int16
4
